// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8hUXl5wukuW0zsw-4zG19TSnMbzIlvL0',
    appId: '1:132844553939:web:68448d3291fa424208b626',
    messagingSenderId: '132844553939',
    projectId: 'prisomtechnology-f690d',
    authDomain: 'prisomtechnology-f690d.firebaseapp.com',
    storageBucket: 'prisomtechnology-f690d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb7vGbOH56AJIEUbVPQk13q8IqbDmrgPE',
    appId: '1:132844553939:android:31d9d2cb38ed58f108b626',
    messagingSenderId: '132844553939',
    projectId: 'prisomtechnology-f690d',
    storageBucket: 'prisomtechnology-f690d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0VC6KZFFkEX_Ec9skVz-63D9XU3nU8z8',
    appId: '1:132844553939:ios:f3bb433ae2d2386b08b626',
    messagingSenderId: '132844553939',
    projectId: 'prisomtechnology-f690d',
    storageBucket: 'prisomtechnology-f690d.appspot.com',
    androidClientId: '132844553939-0lp9lvcnf2gc9vf8nd253khejk2g85hj.apps.googleusercontent.com',
    iosClientId: '132844553939-04pf7mfa8p4pfcbhor1llc1upa7oibjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.prisomtechnology',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0VC6KZFFkEX_Ec9skVz-63D9XU3nU8z8',
    appId: '1:132844553939:ios:f3bb433ae2d2386b08b626',
    messagingSenderId: '132844553939',
    projectId: 'prisomtechnology-f690d',
    storageBucket: 'prisomtechnology-f690d.appspot.com',
    androidClientId: '132844553939-0lp9lvcnf2gc9vf8nd253khejk2g85hj.apps.googleusercontent.com',
    iosClientId: '132844553939-04pf7mfa8p4pfcbhor1llc1upa7oibjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.prisomtechnology',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8hUXl5wukuW0zsw-4zG19TSnMbzIlvL0',
    appId: '1:132844553939:web:8cdd25477823f3ba08b626',
    messagingSenderId: '132844553939',
    projectId: 'prisomtechnology-f690d',
    authDomain: 'prisomtechnology-f690d.firebaseapp.com',
    storageBucket: 'prisomtechnology-f690d.appspot.com',
  );

}